# Generated by Django 3.2.7 on 2021-11-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
    ]
